### ISSUE TITLE
Could i use the frameware on arduino mega2560

### ISSUE THREAD

**Issue by hubery05** [linorobot/linorobot#13]
I am doing a mecanumbot ,can i use the teensy frameware on the arduino mega2560 ?

**Comment by grassjelly** [comment]
Hi,

Can you post the question here: https://groups.google.com/forum/#!forum/linorobot .

Thanks!

**Comment by grassjelly** [comment]
Closing this now. Refer to this thread, if there's any serialization error when using Arduino Mega 2560. https://groups.google.com/forum/#!topic/linorobot/MAbext2sQos

This has been patched on the installer to avoid similar problems:
https://github.com/linorobot/lino_install/commit/106b387c98b9d31386d437d0f8b5b9ade2eb841d
