### ISSUE TITLE
 /teensy code running directly on RPi3 with no Teensy module

### ISSUE THREAD

**Issue by amerkay** [linorobot/linorobot#20]
Hi, amazing work here. 

Quick question, how can I run the /teensy/firmware code directly on a Raspberry Pi 3 with no Teensy module? Is there a port or method without modifiying so many files? I have both the IMU and servo/ESC controller attached to the I2C link directly on the board configured with ROS and Ubuntu.

My setup: ODROID XU4 with Shifter Shield for 3.3V pins, which makes the connectivity similar to RPi3. I have Realsense D435 camera, MPU6050 IMU, PCA9685 ESC/servo controller. All working together with RTABmap and custom ESC controller (documentation will be put online soon).

Thanks!

**Comment by grassjelly** [comment]
Hi,

As we use this more for bug tracking, you can post any non-code related issue/question in the forum instead. Cheers! :)

https://groups.google.com/forum/m/#!forum/linorobot

**Comment by amerkay** [comment]
Oh. Thanks, didn't know about the forum. I just learnt about your work. Cheers :)

**Comment by grassjelly** [comment]
thread link: https://groups.google.com/forum/#!topic/linorobot/2fUmBnzz9Ww
