### ISSUE TITLE
Pinout for the xv11?

### ISSUE THREAD

**Issue by datadrian** [linorobot/linorobot#23]
Is there a pinout on where and how to attach the xv11 lidar? (jetson tx1) Is it connected to the teensy or the jetson gpio?

Also is there an easy way to configure both an xv11 and a kinect to work together?

Thank you, this is an amazing project!

- Adrian

**Comment by grassjelly** [comment]
Hey Adrian,

Can you post your questions here instead as we use this mostly for bug tracking. https://groups.google.com/forum/#!forum/linorobot

Cheers! :)

**Comment by datadrian** [comment]
my bad! please delete!

Adrian Stucker
513.341.LENS

**Comment by grassjelly** [comment]
Closing this. Thread posted here for reference: https://groups.google.com/forum/#!topic/linorobot/DRcIVR6aPFw
