### ISSUE TITLE
Arduino compatibility

### ISSUE THREAD

**Issue by karthikbalu** [linorobot/linorobot#25]
Can Arduino uno be replaced with teensy board? is the code compatible?

Thanks

**Comment by grassjelly** [comment]
Hi, it runs on Teensy by default. Unfortunately you need at least an Arduino Mega to run this. Please refer to the google groups if you have non issue/bug questions. :) Thanks!

**Comment by karthikbalu** [comment]
Thanks a lot for the quick response, im really impressed with this project and going to continue building one :)
