### ISSUE TITLE
Strange thing with Arduino MEGA

### ISSUE THREAD

**Issue by BiggyBaron** [linorobot/linorobot#27]
Dear All,

When porting teensy firmware to Arduino MEGA, there is some magic bug happens.
I do not know why, but after PID controller compute function it can send 257 value to PWM when it goes to backward.

I fix it by hardcoding this dynamic PWM_MAX value in [config file](https://github.com/linorobot/linorobot/blob/master/teensy/firmware/lib/config/lino_base_config.h) by 255 and -255 in PWM_MAX and PWM_MIN.

I have changed firmware to make it okay with Arduino Mega. May I push it to linorobot, so anybody can use it?

**Comment by grassjelly** [comment]
Hi Baron,

Thanks for the PR. As I intent the master branch to be hardware/platform agnostic,  can you send another PR as separate branch (something like)“arduinomega” instead. At least we can point Arduino Mega users to this useful resource until the issues highlighted are resolved and merged in the master branch which also works for all platform. Cheers!
