### ISSUE TITLE
Mecanum robot Y velocity issue

### ISSUE THREAD

**Issue by Razbotics** [linorobot/linorobot#35]
The robot should move left when given positive Y velocity but instead it moves right and also other way around. Why velocity in Y is reversed.

**Comment by grassjelly** [comment]
@Razbotics can you check if your mecanum wheels is in the same orientation as this? https://github.com/linorobot/lino_docs/raw/master/imgs/wiki/2-5.png

**Comment by Razbotics** [comment]
Thanks for the info indeed it was reversed
