### ISSUE TITLE
Possible without encoders???

### ISSUE THREAD

**Issue by ArghyaChatterjee** [linorobot/linorobot#36]
Hello, can anyone suggest me if it is possible to run this robot without wheel encoders? We are using high torque gear motors and it's very difficult to place external encoders on wheels. Can't it calculate the value from the imu data only? If so what's the proccedure ?
Also, built in encoders are not availbale for the kind of motors that we are using. Any kind of suggestion is appreciated. TIA.

**Comment by grassjelly** [comment]
Hi, can you post your question here instead? https://groups.google.com/forum/m/#!forum/linorobot
