### ISSUE TITLE
Motor's rpm and pwm value

### ISSUE THREAD

**Issue by zhuwei** [linorobot/linorobot#39]
The rpm range is 0-330, but the PWM range is 0-255. Is that right? why?
```
motor1_controller.spin(motor1_pid.compute(req_rpm.motor1, current_rpm1));
Controller::spin
analogWrite(pwm_pin_, abs(pwm));
```

**Comment by grassjelly** [comment]
It’s because of the PID which has no idea of the min and max RPM range. It continuously increase/decrease the PWM value depending how big the error between the target RPM and current RPM from the encoders. I’ll close this for now. For non bug issues please post it in the forum.
