### ISSUE TITLE
Ackermann with 4ED

### ISSUE THREAD

**Issue by Dejw4g** [linorobot/linorobot#40]
Hi, 

is it possible to configure it for a 4 wheel drive with Ackermann steering on front wheels?

if not - what is the best "workaround" - switch off rear wheels motors when steering?

**Comment by grassjelly** [comment]
Yes! Please check this library how it is implemented. https://github.com/linorobot/linorobot/blob/master/teensy/firmware/lib/kinematics/Kinematics.cpp

Closing this for now.
