### ISSUE TITLE
pid to pwm 

### ISSUE THREAD

**Issue by bekirbostanci** [linorobot/linorobot#43]
Hi 
I caught my attention while browsing through scripts. You input rpm type value in pid and send the output value directly to the motor as pwm. how did covert this? I didn't understand.

**Comment by grassjelly** [comment]
It’s because the PID’s output will keep changing the value (motor PWM input) based on the error in the encoder until it reaches the target RPM. You can convert it to PWM value by using the CALCULATED_RPM / MAX_RPM * 255 but the behaviour will be the same.

**Comment by bekirbostanci** [comment]
thank you for answer.
