### ISSUE TITLE
On my car, when the speed is set to be less than 0.0157m/s, the car does not respond.

### ISSUE THREAD

**Issue by IAseven** [linorobot/linorobot#54]
I am not a native English speaker，Please forgive my poor English.
Hello, thank you very much for providing such excellent software. I have successfully run your firmware on my own robot, but I found a little problem in my test. I am not sure if it is a bug, here Ask your advice:
My robot is a two-wheeled differential steering tracked vehicle with a wheel diameter of 0.3m. In my test, I found that no matter how I adjust the parameters in lino_base_config.h, I cannot set the minimum linear speed of my car to less than 0.0157 m/ s, after reading the firmware of the lower computer carefully, I found that the getRPM function for calculating the speed in the encode encoder library file returns int type data, and the data returned by the getRPM function in the kinematics library is also int type. During adjustment, if you want the car to move at less than 0.0157m/s, the speed calculated by kinematics.getRPM will be less than 1r/min, and because the int type data is returned, the rpm less than 1r/min will default to 0. The subsequent PID adjustment process will not work. At present, I have changed the data type in the kinematics, encode and other codes to change the problem, and my car can run at a speed less than 0.01m/s.
Please forgive my poor English.

**Comment by grassjelly** [comment]
Hi @IAseven . This thread might help you https://github.com/linorobot/linorobot/issues/50. ). The returned rpm count is returned as integer so anything on that velocity range would be considered negligible (~0)
