### ISSUE TITLE
Status of this project?

### ISSUE THREAD

**Issue by pitosalas** [linorobot/linorobot#59]
Hi @grassjelly -- what a wonderful project this is. I am having a great time with it. I was wondering whether it is still actively maintained or whether  you have moved to other things. It would help me understand whether I want to build my stuff around it. Thanks!

**Comment by pitosalas** [comment]
I am thinking that the lack of response means that @grassjelly is no longer actively engaged? Is there another official maintainer?

**Comment by IAseven** [comment]
@pitosalas As far as I know, the author currently focuses on the quadruped robot project, link: https://github.com/chvmp

**Comment by Russ76** [comment]
@pitosalas If you build with nearly the same thing as in these lists, it should still work. There might be some small issues. The Python version 2.7 is not supported by Platformio now, and I'm trying to work around that. I'm also using ROS Melodic. I'd say, Dive In! Juan still does answer issues here but in his time.

**Comment by pitosalas** [comment]
Ok. So there's no active maintenance just the occasional response from @grassjelly . I will try a pull request and see what happens!
