### ISSUE TITLE
ydlidar package is out of date

### ISSUE THREAD

**Issue by pitosalas** [linorobot/linorobot#60]
At least from my personal experience. The version of the ydlidar package that is included in the linorobot is out of date and doesn't work correctly. I was able to solve my problem my using the current package: https://github.com/YDLIDAR/ydlidar_ros. It is called ydlidar-ros while linorobot refers to it as just ydlidar so some renaming was necessary as well.

**Comment by IAseven** [comment]
@pitosalas If your radar is rplidar, it is recommended that you use the latest ros driver package: https://github.com/YDLIDAR/ydlidar_ros_driver

**Comment by Russ76** [comment]
Thanks for this info, I'm also using Ydlidar, and making a machine right now.
