### ISSUE TITLE
firmware not finding lino_msgs/Velocities.h

### ISSUE THREAD

**Issue by mukmalone** [linorobot/linorobot#62]
Hi,
I have this error `/home/michael/catkin_ws/src/linorobot/teensy/firmware/src/firmware/firmware.ino:12:34: fatal error: lino_msgs/Velocities.h: No such file or directory`

I've cloned the package `lino_msgs` into my catkin workspace and was able to successfully to catkin_make with no errors.

Let me know if you have any clues as to what I might have missed.
Thank you,
Michael

**Comment by mukmalone** [comment]
Non-issue.  Wasn't following correct steps.

**Comment by usama0300854** [comment]
how did you fix this error..please help me out
