### ISSUE TITLE
Hello,encoder problem

### ISSUE THREAD

**Issue by zhangstar3** [linorobot/linorobot#7]
hi,I have a question for a long time.Now i want to make a car with the mecanum wheel,and I have Arduino Mega2560,motor dirver...,enen,I cheak the Mega2560 have 6 pins for interrupts(2,3,18,19,20,21 pins).But we have 4 wheels,and can we use analog pin for the interrupts to count the encoders.pelase forgive my poor English，Looking forward to your reply！

**Comment by grassjelly** [comment]
Hi can you post your questions here instead? https://groups.google.com/forum/#!forum/linorobot . Thanks!

**Comment by grassjelly** [comment]
This has been posted in the project's forum. Closing this.
