### ISSUE TITLE
MPU6050 Support

### ISSUE THREAD

**Issue by 12458** [linorobot/linorobot#8]
Any idea when MPU6050 support is going to be implemented?

**Comment by grassjelly** [comment]
I’m planning to release MPU6050 support early next year. The release will include support for brushless motor ESCs as well . Currently busy working on another robot platform that includes MoveIt integration: https://github.com/grassjelly/onine . You may join our group to  get the recent updates. https://groups.google.com/forum/m/#!forum/linorobot . Thanks!

**Comment by grassjelly** [comment]
Just for the record, MPU6050 is now supported. Please check out Master branch.
