### ISSUE TITLE
The tangential velocity for 2wd is doubled

### ISSUE THREAD

**Issue by dandare1972** [linorobot/linorobot#9]
I have a 2WD platform on the caterpillar tracks. Angular velocity shows 2 times more.
It is possible that the radius is incorrectly specified when calculating the tangential velocity.

**Comment by grassjelly** [comment]
Thanks for reporting the bug. 

This has been resolved: https://github.com/linorobot/linorobot/commit/6c00dce0bbc637d8f64026d0eb9d0dea6b5efdac

Putting the thread's link here as well for reference: https://groups.google.com/forum/#!topic/linorobot/Jf2X4OHWAzY
